# packageExtensions:
#   "@apollo/federation@^0.23.0":
#     dependencies:
#       core-js: ^3.0.1
#   "@apollo/gateway@^0.26.0":
#     dependencies:
#       node-fetch: ^2.2.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.4.1.cjs

pnpFallbackMode: none
